module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      screens: {
        "hover-hover": { raw: "(hover: hover)" },
      },
      spacing: {
        112: "28rem",
      },
      backgroundImage: {
        americano: "url('./cocktail-photos/americano.jpg')",
        "aperol-spritz": "url('./cocktail-photos/aperol-spritz.jpg')",
        "black-russian": "url('./cocktail-photos/black-russian.jpg')",
        boulevardier: "url('./cocktail-photos/boulevardier.jpg')",
        caipirinha: "url('./cocktail-photos/caipirinha.jpg')",
        carajillo: "url('./cocktail-photos/carajillo.jpg')",
        "champagne-cocktail": "url('./cocktail-photos/champagne-cocktail.jpg')",
        "coffee-negroni": "url('./cocktail-photos/coffee-negroni.jpg')",
        "coming-soon": "url('./cocktail-photos/coming-soon.jpg')",
        "corpse-reviver-2": "url('./cocktail-photos/corpse-reviver-2.jpg')",
        cosmopolitan: "url('./cocktail-photos/cosmopolitan.jpg')",
        daiquiri: "url('./cocktail-photos/daiquiri.jpg')",
        "dirty-martini": "url('./cocktail-photos/dirty-martini.jpg')",
        "espresso-martini": "url('./cocktail-photos/espresso-martini.jpg')",
        "gin-and-tonic": "url('./cocktail-photos/gin-and-tonic.jpg')",
        "hemingway-daiquiri": "url('./cocktail-photos/hemingway-daiquiri.jpg')",
        "irish-coffee": "url('./cocktail-photos/irish-coffee.jpg')",
        "kingston-negroni": "url('./cocktail-photos/kingston-negroni.jpg')",
        "last-word": "url('./cocktail-photos/last-word.jpg')",
        "lemon-drop": "url('./cocktail-photos/lemon-drop.jpg')",
        manhattan: "url('./cocktail-photos/manhattan.jpg')",
        margarita: "url('./cocktail-photos/margarita.jpg')",
        martini: "url('./cocktail-photos/martini.jpg')",
        martinez: "url('./cocktail-photos/martinez.jpg')",
        "milano-torino": "url('./cocktail-photos/milano-torino.jpg')",
        "mint-julep": "url('./cocktail-photos/mint-julep.jpg')",
        "moscow-mule": "url('./cocktail-photos/moscow-mule.jpg')",
        mojito: "url('./cocktail-photos/mojito.jpg')",
        negroni: "url('./cocktail-photos/negroni.jpg')",
        "negroni-sbagliato": "url('./cocktail-photos/negroni-sbagliato.jpg')",
        "new-york-sour": "url('./cocktail-photos/new-york-sour.jpg')",
        "oaxaca-old-fashioned":
          "url('./cocktail-photos/oaxaca-old-fashioned.jpg')",
        "old-fashioned": "url('./cocktail-photos/old-fashioned.jpg')",
        paloma: "url('./cocktail-photos/paloma.jpg')",
        "paper-plane": "url('./cocktail-photos/paper-plane.jpg')",
        "pisco-sour": "url('./cocktail-photos/pisco-sour.jpg')",
        sazerac: "url('./cocktail-photos/sazerac.jpg')",
        sidecar: "url('./cocktail-photos/sidecar.jpg')",
        southside: "url('./cocktail-photos/southside.jpg')",
        "tequila-sunrise": "url('./cocktail-photos/tequila-sunrise.jpg')",
        vesper: "url('./cocktail-photos/vesper.jpg')",
        "whiskey-sour": "url('./cocktail-photos/whiskey-sour.jpg')",
      },
      fontFamily: {
        cursive: ['"Work Sans"', "font"],
      },
    },
  },
  plugins: [],
};
