export const cocktails = [
  {
    name: "Americano",
    ingredients: ["Sweet Vermouth", "Campari", "Club Soda"],
    garnish: "Orange Twist",
    glassware: "Collins Glass",
    amounts: ["1.5 oz", "1.5 oz", "Top with"],
    tags: ["Bitter", "Bubbly", "Classic", "Low ABV"],
    photoString: "bg-americano",
    facts: [
      "The Americano is the precursor to the Negroni.",
      `It is the first drink ordered by James Bond in the first novel in Ian Fleming's series, Casino Royale. In From Russia With Love, Bond drinks "Two excellent Americanos" in Rome during his flight to Istanbul.`,
    ],
  },
  {
    name: "Aperol Spritz",
    ingredients: ["Aperol", "Prosecco", "Club Soda"],
    garnish: "Orange Wedge",
    glassware: "Wine Glass",
    amounts: ["2 oz", "3 oz", "1 oz", ""],
    tags: ["Aperitif", "Refreshing", "Bubbly", "Low ABV"],
    photoString: "bg-aperol-spritz",
  },
  {
    name: "Aviation",
    ingredients: [
      "Gin",
      "Maraschino Liqueur",
      "Creme de Violette",
      "Lemon Juice",
    ],
    garnish: "Cherry",
    glassware: "Large Coupe",
    amounts: ["2 oz", "0.5 oz", "0.25 oz", "0.75 oz"],
    tags: ["Classic", "Floral"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Bijou",
    createdBy: "Harry Johnson",
    ingredients: [
      "Gin",
      "Sweet Vermouth",
      "Green Chartreuse",
      "Orange Bitters",
    ],
    garnish: ["Cherry", "None"],
    glassware: "Small Coupe",
    amounts: ["1 oz", "1 oz", "1 oz", "2 dashes"],
    tags: ["Classic", "Simple"],
    photoString: "bg-coming-soon",
    facts: ["Bijou is French for jewel."],
  },
  {
    name: "Black Manhattan",
    createdBy: "Todd Smith",
    ingredients: [
      "Rye Whiskey",
      "Averna",
      "Angostura Bitters",
      "Orange Bitters",
    ],
    garnish: "Cherry",
    glassware: "Small Coupe",
    amounts: ["2 oz", "1 oz", "1 dash", "1 dash"],
    photoString: "bg-coming-soon",
    tags: ["Bitter"],
  },
  {
    name: "Black Russian",
    ingredients: ["Vodka", "Coffee Liqueur", "Simple Syrup"],
    garnish: "None",
    glassware: "Double Old-Fashioned Glass",
    amounts: ["2 oz", "1 oz", "0.25 oz"],
    photoString: "bg-black-russian",
    tags: ["Classic", "Coffee"],
  },
  {
    name: "Boulevardier",
    ingredients: [["Bourbon", "Rye Whiskey"], "Sweet Vermouth", "Campari"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    amounts: ["1 oz", "1 oz", "1 oz"],
    tags: ["Bitter", "Spirit-Forward"],
    photoString: "bg-boulevardier",
    facts: [
      "The Boulevardier is simply a variation on the classic Negroni that is adored for its deft Balance of Bitters, boozy and sweet.",
      "While the gin-based Negroni is crisp and bracing, the whiskey-based Boulevardier is rich and warming.",
    ],
  },
  {
    name: "Caipirinha",
    ingredients: ["Cachaça", "Lime Wedges", "Sugar"],
    garnish: "None",
    glassware: "Double Old-Fashioned Glass",
    amounts: ["2 oz", "8", "2 tsp"],
    tags: ["Refreshing"],
    photoString: "bg-caipirinha",
    facts: [
      "The Caipirinha is Brazil's national drink, and cachaça is the country's national spirit.",
    ],
  },
  {
    name: "Carajillo",
    ingredients: ["Espresso", "Licor 43"],
    amounts: ["1.5 oz", "1.5 oz"],
    garnish: ["Orange Twist", "Coffee Beans", "Cinnamon Powder"],
    glassware: ["Small Coupe", "Double Old-Fashioned Glass"],
    tags: ["Low ABV", "Simple"],
    photoString: "bg-carajillo",
    facts: [
      "A classic Spanish cocktail, popular in Mexico.",
      "According to folk etymology, its origin dates to the times when Cuba was a Spanish province. The troops combined coffee with Rum to give them courage. Spanish coraje means courage, and its diminutive form is corajillo, later changing to carajillo.",
    ],
  },
  {
    name: "Champagne Cocktail",
    ingredients: ["Champagne", "Sugar Cube", "Angostura Bitters"],
    amounts: ["5 oz", "1", "4 dashes", ""],
    garnish: "Lemon Twist",
    glassware: "Wine Glass",
    tags: ["Bubbly", "Classic"],
    photoString: "bg-champagne-cocktail",
    facts: [
      "This simple classic originally appeared in 'The Bartender’s Guide,' an 1862 tome by Jerry Thomas.",
    ],
  },
  {
    name: "Coffee Negroni",
    ingredients: ["Gin", "Sweet Vermouth", "Campari", "Coffee Liqueur"],
    amounts: ["1 oz", "0.75 oz", "0.75 oz", "0.5 oz"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    tags: ["Bitter", "Classic", "Coffee"],
    photoString: "bg-coffee-negroni",
  },
  {
    name: "Corpse Reviver #2",
    ingredients: [
      "Gin",
      "Lillet Blanc",
      "Lemon Juice",
      "Orange Liqueur",
      "Absinthe",
    ],
    garnish: "Lemon Twist",
    glassware: "Small Coupe",
    amounts: ["0.75 oz", "0.75 oz", "0.75 oz", "0.75 oz", "Rinse with"],
    tags: ["Tart"],
    photoString: "bg-corpse-reviver-2",
  },
  {
    name: "Cosmopolitan",
    ingredients: ["Vodka", "Orange Liqueur", "Lime Juice", "Cranberry Juice"],
    amounts: ["2 oz", "1 oz", "0.75 oz", "0.25 oz"],
    garnish: "Lime Wheel",
    glassware: "Large Coupe",
    tags: ["Tart", "Classic"],
    photoString: "bg-cosmopolitan",
  },
  {
    name: "Daiquiri",
    ingredients: [["White Rum", "Dark Rum"], "Lime Juice", "Simple Syrup"],
    amounts: ["2 oz", "0.75 oz", "1 oz"],
    garnish: "Lime Wheel",
    glassware: "Small Coupe",
    tags: ["Tart", "Tiki", "Classic"],
    photoString: "bg-daiquiri",
  },
  {
    name: "Dark and Stormy",
    ingredients: ["Dark Rum", "Ginger Beer", "Lime Juice"],
    amounts: ["2 oz", "3 oz", "0.5 oz"],
    garnish: "Lime Wheel",
    glassware: "Collins Glass",
    tags: ["Citrusy", "Bubbly"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Dirty Martini",
    ingredients: [["Gin", "Vodka"], "Olive Brine"],
    amounts: ["2.5 oz", "0.5 oz"],
    garnish: "Olive(s)",
    glassware: "Small Coupe",
    tags: ["Spirit-Forward", "Savory"],
    photoString: "bg-dirty-martini",
  },
  {
    name: "Eastside",
    ingredients: [
      "Gin",
      "Lime Juice",
      "Cucumber",
      "Mint Leaves",
      "Simple Syrup",
    ],
    garnish: "Lime Wheel",
    glassware: "Large Coupe",
    amounts: ["2 oz", "0.75 oz", "4-5 wheels", "8-12", "1 oz"],
    tags: ["Personal Favorite", "Refreshing"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Espresso Martini",
    ingredients: ["Vodka", "Espresso", "Coffee Liqueur", "Vanilla Syrup"],
    amounts: ["2 oz", "1.5 oz", "0.5 oz", "0.5 oz"],
    garnish: "Coffee Beans",
    glassware: "Large Coupe",
    tags: ["Modern Classic", "Personal Favorite"],
    photoString: "bg-espresso-martini",
  },
  {
    name: "French 75",
    ingredients: ["Gin", "Lemon", "Simple Syrup", "Champagne"],
    amounts: ["1 oz", "0.5 oz", "0.5 oz", "Top with 3 oz"],
    garnish: "Lemon Twist",
    glassware: "Wine Glass",
    tags: ["Citrusy", "Bubbly", "Classic"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Gimlet",
    ingredients: [["Gin", "Vodka"], "Lime Juice", "Simple Syrup"],
    amounts: ["2 oz", "0.75 oz", "1 oz"],
    garnish: "Lime Wheel",
    glassware: "Large Coupe",
    tags: ["Tart", "Refreshing", "Classic"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Gin & Tonic",
    ingredients: ["Gin", "Tonic"],
    amounts: ["2 oz", "3 oz"],
    garnish: ["Lime Wheel", "Fruits", "Herbs"],
    glassware: ["Double Old-Fashioned Glass", "Wine Glass"],
    tags: ["Bubbly", "Refreshing", "Classic", "Simple", "Personal Favorite"],
    photoString: "bg-gin-and-tonic",
    facts: ["The gin & tonic is the national cocktail of Spain."],
  },
  {
    name: "Gin Fizz",
    ingredients: [
      "Gin",
      "Lemon Juice",
      "Simple Syrup",
      "Egg White",
      "Club Soda",
    ],
    amounts: ["2 oz", "0.75 oz", "1 oz", "1", "Top with"],
    garnish: ["Bitters", "None"],
    glassware: "Collins Glass",
    tags: ["Classic", "Bubbly"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Greyhound",
    ingredients: ["Vodka", "Grapefruit Juice"],
    amounts: ["2 oz", "3 oz"],
    garnish: "Grapefruit Wedge",
    glassware: "Double Old-Fashioned Glass",
    tags: ["Simple", "Refreshing"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Hanky Panky",
    createdBy: "Ada Coleman",
    ingredients: ["Gin", "Sweet Vermouth", "Fernet-Branca"],
    amounts: ["1.5 oz", "1.5 oz", "2 dashes"],
    garnish: "Orange Twist",
    glassware: "Small Coupe",
    tags: ["Classic"],
    photoString: "bg-coming-soon",
    facts: [
      "Hanky Panky is also the name of one of the best bars in the world, located in Mexico City.",
    ],
  },
  {
    name: "Hemingway Daiquiri",
    ingredients: [
      "White Rum",
      "Maraschino Liqueur",
      "Lime Juice",
      "Grapefruit Juice",
    ],
    amounts: ["2 oz", "0.5 oz", "0.75 oz", "0.5 oz"],
    garnish: "Lime Wheel",
    glassware: "Large Coupe",
    tags: ["Classic"],
    photoString: "bg-hemingway-daiquiri",
  },
  {
    name: "Irish Coffee",
    ingredients: [
      "Irish Whiskey",
      "Simple Syrup",
      "Hot Coffee",
      "Whipped Cream",
    ],
    amounts: ["2 oz", "1 oz", "4 oz", "Top with"],
    garnish: ["Cinnamon Powder", "Shaved Chocolate", "None"],
    glassware: "Irish Coffee Mug",
    tags: ["Classic", "Coffee", "Hot"],
    photoString: "bg-irish-coffee",
  },
  {
    name: "Jungle Bird",
    ingredients: [
      "Dark Rum",
      "Campari",
      "Pineapple Juice",
      "Lime Juice",
      "Simple Syrup",
    ],
    amounts: ["2 oz", "0.75 oz", "2 oz", "0.5 oz", "0.5 oz"],
    garnish: "Pineapple Wedge",
    glassware: "Double Old Fashioned-Glass",
    tags: ["Tiki", "Refreshing", "Fruity"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Kingston Negroni",
    ingredients: ["Dark Rum", "Sweet Vermouth", "Campari"],
    amounts: ["1 oz", "1 oz", "1 oz"],
    garnish: "Orange Twist",
    glassware: "Old Fashioned-Glass",
    tags: ["Bitter", "Spirit-Forward"],
    photoString: "bg-kingston-negroni",
  },
  {
    name: "Kir Royale",
    ingredients: ["Champagne", "Creme de Cassis"],
    amounts: ["4.5 oz", "0.5 oz"],
    garnish: "Lemon Twist",
    glassware: ["Champagne Flute", "Wine Glass"],
    tags: ["Bubbly", "Low ABV"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Last Word",
    ingredients: [
      "Gin",
      "Green Chartreuse",
      "Maraschino Liqueur",
      "Lime Juice",
    ],
    amounts: ["0.75 oz", "0.75 oz", "0.75 oz", "0.75 oz"],
    garnish: "Cherry",
    glassware: "Small Coupe",
    tags: ["Tart", "Personal Favorite"],
    photoString: "bg-last-word",
  },
  {
    name: "Lemon Drop",
    ingredients: ["Vodka", "Lemon Juice", "Simple Syrup"],
    amounts: ["2 oz", "0.75 oz", "1 oz"],
    garnish: ["Sugar Rim", "Lemon Twist", "Lemon Wheel"],
    glassware: "Large Coupe",
    tags: ["Sour", "Tart"],
    photoString: "bg-lemon-drop",
  },
  {
    name: "Mai Tai",
    ingredients: [
      "White Rum",
      "Dark Rum",
      "Orange Liqueur",
      "Lime Juice",
      "Orgeat",
    ],
    amounts: ["1.5 oz", "0.5 oz", "0.75 oz", "1 oz", "0.5 oz"],
    garnish: "Mint Sprig",
    glassware: "Double Old-Fashioned Glass",
    tags: ["Tiki", "Classic", "Refreshing"],
    photoString: "bg-coming-soon",
  },
  {
    name: "Manhattan",
    ingredients: [["Bourbon", "Rye"], "Sweet Vermouth", "Angostura Bitters"],
    garnish: "Cherry",
    glassware: "Small coupe",
    amounts: ["2 oz", "1 oz", "2 dashes"],
    tags: ["Classic", "Spirit-Forward"],
    photoString: "bg-manhattan",
  },
  {
    name: "Margarita",
    ingredients: [
      ["Tequila", "Mezcal"],
      "Orange Liqueur",
      "Agave Syrup",
      "Lime Juice",
    ],
    amounts: ["2 oz", "0.5 oz", "0.5 oz", "0.75 oz", ""],
    garnish: ["Lime Wedge", "Salt Rim"],
    glassware: "Double Old-Fashioned Glass",
    tags: ["Tart", "Classic", "Personal Favorite"],
    photoString: "bg-margarita",
  },
  {
    name: "Martinez",
    ingredients: [
      "Gin",
      "Sweet Vermouth",
      "Maraschino Liqueur",
      "Angostura Bitters",
    ],
    amounts: ["1.5 oz", "1.5 oz", "0.25 oz", "2 dashes"],
    tags: ["Classic", "Spirit-Forward"],
    garnish: "Cherry",
    glassware: "Small Coupe",
    photoString: "bg-martinez",
    facts: ["This cocktail is the predecessor of the Martini."],
  },
  {
    name: "Martini",
    ingredients: [["Gin", "Vodka"], "Dry Vermouth", "Orange Bitters"],
    amounts: ["3 oz", "0 oz", "0 dashes"],
    garnish: ["Lemon twist", "Olives"],
    glassware: "Small Coupe",
    tags: ["Classic", "Spirit-Forward"],
    photoString: "bg-martini",
  },
  {
    name: "Milano Torino",
    ingredients: ["Sweet Vermouth", "Campari"],
    amounts: ["1.5 oz", "1.5 oz"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    tags: ["Classic", "Simple", "Bitter"],
    photoString: "bg-milano-torino",
  },
  {
    name: "Mint Julep",
    ingredients: ["Bourbon", "Mint Leaves", "Simple Syrup"],
    amounts: ["2 oz", "8-10", "0.25 oz"],
    garnish: "Mint sprig",
    glassware: "Mint Julep Cup",
    tags: ["Classic", "Simple", "Refreshing"],
    photoString: "bg-mint-julep",
    facts: [
      "The mint julep has been promoted by Churchill Downs in association with the Kentucky Derby since 1938. As of 2009, about 120,000 juleps were served at Churchill Downs over the two-day period of the Kentucky Oaks and the Kentucky Derby, virtually all of them in specially made Kentucky Derby collectible glasses.",
    ],
  },
  {
    name: "Mojito",
    ingredients: [
      "White Rum",
      "Lime Juice",
      "Simple Syrup",
      "Mint Leaves",
      "Club Soda",
    ],
    amounts: ["2 oz", "0.75 oz", "1 oz", "8-10", "Top with"],
    garnish: "Mint Sprig",
    glassware: "Collins Glass",
    tags: ["Classic", "Refreshing", "Bubbly"],
    photoString: "bg-mojito",
  },
  {
    name: "Moscow Mule",
    ingredients: ["Vodka", "Ginger Beer", "Lime Juice"],
    amounts: ["2 oz", "0.75 oz", "Top with"],
    garnish: ["Lime Wheel", "Bitters"],
    glassware: ["Copper Mug", "Collins Glass"],
    tags: ["Bubbly", "Refreshing"],
    photoString: "bg-moscow-mule",
  },
  {
    name: "Naked and Famous",
    createdBy: "Joaquín Simó",
    ingredients: ["Mezcal", "Aperol", "Yellow Chartreuse", "Lime Juice"],
    amounts: ["0.75 oz", "0.75 oz", "0.75 oz", "0.75 oz"],
    garnish: ["Lime Wheel"],
    glassware: ["Small Coupe"],
    tags: ["Tart", "Refreshing"],
    photoString: "bg-coming-soon",
  },

  {
    name: "Negroni",
    createdBy: "Count Camillo Negroni",
    ingredients: ["Gin", "Sweet Vermouth", "Campari"],
    amounts: ["1 oz", "1 oz", "1 oz"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    tags: [
      "Bitter",
      "Spirit-Forward",
      "Aperitif",
      "Classic",
      "Personal Favorite",
    ],
    photoString: "bg-negroni",
    facts: [
      "In 1919, Pascal Olivier Count de Negroni concocted it by asking the bartender, Fosco Scarselli, to strengthen his personal Favorite cocktail, the Americano, by adding gin rather than the normal club soda.",
    ],
  },
  {
    name: "Negroni Sbagliato",
    ingredients: ["Prosecco", "Sweet Vermouth", "Campari"],
    amounts: ["3 oz", "1 oz", "1 oz"],
    garnish: "Orange Wedge",
    glassware: "Wine Glass",
    tags: ["Aperitif", "Bubbly"],
    photoString: "bg-negroni-sbagliato",
    facts: [
      "A classic negroni contains equal parts gin, Vermouth, and Campari, while a sbagliato, which translates to “mistake” in Italian, swaps prosecco for gin. Supposedly, a bartender grabbed sparkling wine instead of the spirit as he was making a negroni, and the drink stuck.",
    ],
  },
  {
    name: "New York Sour",
    createdBy: "Allen Katz",
    ingredients: [
      ["Bourbon", "Rye Whiskey"],
      "Lemon Juice",
      "Simple Syrup",
      "Egg White",
      "Red Wine",
    ],
    amounts: ["2 oz", "0.75 oz", "1 oz", "0.75 oz", "0.5 oz"],
    garnish: "None",
    glassware: "Large Coupe",
    tags: ["Classic", "Sour"],
    photoString: "bg-new-york-sour",
    facts: [
      "Reports trace the New York Sour back to the 1870s or 1880s, although it operated under other names during this time, including the Continental Sour.",
      "It’s possible that the New York Sour was created in Chicago, but in time, the New York label grabbed on and never let go.",
    ],
  },
  {
    name: "Oaxaca Old Fashioned",
    ingredients: ["Mezcal", "Sugar Cube", "Mole Bitters"],
    amounts: ["1 oz", "1", "3-4 dashes of"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    photoString: "bg-oaxaca-old-fashioned",
    tags: ["Spirit-Forward", "Simple"],
  },
  {
    name: "Old Fashioned",
    ingredients: [
      ["Bourbon", "Rye Whiskey"],
      "Sugar Cube",
      "Angostura Bitters",
      "Orange twist",
    ],
    amounts: ["2 oz", "1", "3 dashes", "Orange twist"],
    garnish: "Orange Twist",
    glassware: "Old-Fashioned Glass",
    tags: ["Simple", "Spirit-Forward", "Classic"],
    photoString: "bg-old-fashioned",
    facts: [
      `The first documented definition of the word "Cocktail" was in response to a reader's letter asking to define the word in the 6 May 1806, issue of The Balance and Columbian Repository in Hudson, New York. In the 13 May 1806, issue, the paper's editor wrote that it was a potent concoction of spirits, Bitters, water, and sugar; it was also referred to at the time as a Bittersed sling and is essentially the recipe for an old fashioned.`,
    ],
  },

  {
    name: "Paloma",
    ingredients: ["Tequila", "Lime Juice", "Grapefruit Soda"],
    amounts: ["2 oz", "0.75 oz", "Top with"],
    garnish: ["Grapefruit Wedge", "Lime Wheel"],
    glassware: "Collins Glass",
    photoString: "bg-paloma",
    tags: ["Simple", "Refreshing", "Citrusy"],
  },
  {
    name: "Paper Plane",
    createdBy: "Sam Ross",
    ingredients: ["Bourbon", "Aperol", "Amaro Nonino", "Lemon Juice"],
    amounts: ["0.75 oz", "0.75 oz", "0.75 oz", "0.75 oz"],
    garnish: "Lemon Twist",
    glassware: "Small Coupe",
    photoString: "bg-paper-plane",
    tags: ["Tart", "Modern Classic"],
  },
  {
    name: "Penicillin",
    ingredients: ["Scotch", "Honey Syrup", "Ginger Syrup", "Lemon Juice"],
    amounts: ["2 oz", "0.5 oz", "0.5 oz", "0.75 oz"],
    garnish: ["Lemon Wheel", "Candied Ginger"],
    glassware: "Double Old-Fashioned Glass",
    photoString: "bg-coming-soon",
    tags: ["Tart", "Smoky", "Modern Classic"],
    createdBy:
      "Created by Sam Ross in the mid-2000s, when he was working at New York City’s famous Milk & Honey bar",
  },
  {
    name: "Pisco Sour",
    ingredients: ["Pisco", "Lemon Juice", "Simple Syrup"],
    amounts: ["2 oz", "0.75 oz", "1 oz"],
    garnish: "Bitters Design",
    glassware: "Large Coupe",
    photoString: "bg-pisco-sour",
    tags: ["Sour"],
  },
  {
    name: "Sazerac",
    ingredients: [
      "Rye Whiskey",
      "Sugar Cube",
      "Peychaud's Bitters",
      "Absinthe",
    ],
    amounts: ["2 oz", "1", "4 dashes", "Rinse with or spray"],
    garnish: "Lemon Twist",
    glassware: "Old-Fashioned Glass",
    photoString: "bg-sazerac",
    tags: ["Spirit-Forward"],
  },
  {
    name: "Sidecar",
    ingredients: ["Brandy", "Orange Liqueur", "Lemon Juice"],
    amounts: ["2 oz", "1 oz", "0.75 oz"],
    garnish: "Sugar Rim",
    glassware: "Large Coupe",
    photoString: "bg-sidecar",
    tags: ["Classic", "Sour"],
  },
  {
    name: "Southside",
    ingredients: ["Gin", "Lime Juice", "Simple Syrup", "Mint Leaves"],
    amounts: ["2 oz", "0.75 oz", "1 oz", "10-12"],
    garnish: "Lime Wheel",
    glassware: "Large Coupe",
    photoString: "bg-southside",
    tags: ["Personal Favorite", "Refreshing", "Tart"],
  },

  {
    name: "Tequila Sunrise",
    ingredients: ["Tequila", "Orange Juice", "Grenadine"],
    amounts: ["2 oz", "4 oz", "0.25 oz"],
    garnish: "Cherry",
    glassware: ["Collins Glass"],
    photoString: "bg-tequila-sunrise",
    tags: ["Citrusy", "Refreshing"],
  },
  {
    name: "Tom Collins",
    ingredients: ["Gin", "Lemon Juice", "Simple Syrup", "Club Soda"],
    amounts: ["2 oz", "0.75 oz", "1 oz", "Top with"],
    garnish: "Lemon Wheel",
    glassware: "Collins Glass",
    photoString: "bg-coming-soon",
    tags: ["Bubbly", "Refreshing", "Classic"],
  },
  {
    name: "Trinidad Sour",
    createdBy: "Giuseppe González",
    ingredients: ["Angostura Bitters", "Rye Whiskey", "Lemon Juice", "Orgeat"],
    amounts: ["1.5 oz", "0.5 oz", "0.75 oz", "1 oz"],
    garnish: "Lemon Twist",
    glassware: "Large Coupe",
    photoString: "bg-coming-soon",
    tags: ["Rich", "Tart"],
  },
  {
    name: "Vesper",
    ingredients: ["Gin", "Vodka", "Lillet Blanc"],
    amounts: ["3 oz", "1 oz", "0.5 oz"],
    photoString: "bg-vesper",
    garnish: "Lemon Twist",
    glassware: "Large Coupe",
    tags: ["Classic", "Spirit-Forward"],
    facts: [
      "The original calls for Kina Lillet, but that product was discontinued.",
      "The drink was invented and named by Ian Fleming in the 1953 James Bond novel Casino Royale.",
    ],
  },
  {
    name: "Whiskey Sour",
    ingredients: [
      "Bourbon",
      "Lemon Juice",
      "Simple Syrup",
      "Egg White",
      "Angostura Bitters",
    ],
    garnish: "Bitters Design",
    glassware: "Large Coupe",
    amounts: ["2 oz", "0.75 oz", "1 oz", "1", "Garnish with"],
    photoString: "bg-whiskey-sour",
    tags: ["Classic", "Sour"],
  },

  {
    name: "White Negroni",
    createdBy: "Wayne Collins",
    ingredients: ["Gin", "Lillet Blanc", "Suze"],
    amounts: ["1.5 oz", "1 oz", "0.5 oz"],
    garnish: "Lemon Twist",
    glassware: "Old-Fashioned Glass",
    photoString: "bg-coming-soon",
    tags: ["Bitter", "Floral"],
  },
  {
    name: "White Russian",
    ingredients: ["Vodka", "Coffee Liqueur", "Simple Syrup", "Heavy Cream"],
    amounts: ["2 oz", "1 oz", "0.25 oz", "Top with"],
    garnish: ["Coffee Beans", "Cinnamon Powder", "Grated Nutmeg"],
    glassware: "Double Old-Fashioned Glass",
    photoString: "bg-coming-soon",
    tags: ["Classic", "Coffee", "Creamy"],
  },
];

export const categories = [
  {
    name: "Spirits",
    items: [
      "Absinthe",
      "Bourbon",
      "Brandy",
      "Cachaça",
      "Dark Rum",
      "Gin",
      "Irish Whiskey",
      "Mezcal",
      "Pisco",
      "Rye Whiskey",
      "Scotch",
      "Tequila",
      "Vodka",
      "White Rum",
    ],
    tailwindBG: "bg-orange-500",
    tailwindBorder: "border-orange-500",
    hoverBorder: "hover:border-orange-500",
    hoverTextColor: "hover:text-orange-500",
    tailwindTextColor: "text-orange-500",
  },
  {
    name: "Vermouth",
    items: ["Dry Vermouth", "Sweet Vermouth", "Lillet Blanc"],
    tailwindBG: "bg-red-700",
    tailwindBorder: "border-red-700",
    hoverBorder: "hover:border-red-700",
    hoverTextColor: "hover:text-red-700",
    tailwindTextColor: "text-red-700",
  },
  {
    name: "Amari",
    items: [
      "Amaro Montenegro",
      "Amaro Nonino",
      "Amaro Ramazzotti",
      "Aperol",
      "Averna",
      "Campari",
      "Fernet-Branca",
      "Suze",
    ],
    tailwindBG: "bg-pink-500",
    tailwindBorder: "border-pink-500",
    hoverBorder: "hover:border-pink-500",
    hoverTextColor: "hover:text-pink-500",
    tailwindTextColor: "text-pink-500",
  },
  {
    name: "Liqueurs",
    items: [
      "Creme de Cacao",
      "Creme de Cassis",
      "Creme de Violette",
      "Coffee Liqueur",
      "Green Chartreuse",
      "Licor 43",
      "Maraschino Liqueur",
      "Orange Liqueur",
    ],
    tailwindBG: "bg-purple-500",
    tailwindBorder: "border-purple-500",
    hoverBorder: "hover:border-purple-500",
    hoverTextColor: "hover:text-purple-500",
    tailwindTextColor: "text-purple-500",
  },
  {
    name: "Juices",
    items: [
      "Cranberry Juice",
      "Grapefruit Juice",
      "Lemon Juice",
      "Lime Juice",
      "Orange Juice",
    ],
    tailwindBG: "bg-lime-600",
    tailwindBorder: "border-lime-600",
    hoverBorder: "hover:border-lime-600",
    hoverTextColor: "hover:text-lime-600",
    tailwindTextColor: "text-lime-600",
  },
  {
    name: "Bubbles",
    items: [
      "Champagne",
      "Club Soda",
      "Cola",
      "Ginger Beer",
      "Grapefruit Soda",
      "Prosecco",
      "Tonic",
    ],
    tailwindBG: "bg-cyan-600",
    tailwindBorder: "border-cyan-600",
    hoverBorder: "hover:border-cyan-600",
    hoverTextColor: "hover:text-cyan-600",
    tailwindTextColor: "text-cyan-600",
  },
  {
    name: "Syrups",
    items: [
      "Agave Syrup",
      "Ginger Syrup",
      "Honey Syrup",
      "Orgeat",
      "Simple Syrup",
      "Vanilla Syrup",
    ],
    tailwindBG: "bg-blue-800",
    tailwindBorder: "border-blue-800",
    hoverBorder: "hover:border-blue-800",
    hoverTextColor: "hover:text-blue-800",
    tailwindTextColor: "text-blue-800",
  },
  {
    name: "Bitters",
    items: [
      "Angostura Bitters",
      "Chocolate Bitters",
      "Mole Bitters",
      "Orange Bitters",
      "Peychaud's Bitters",
    ],
    tailwindBG: "bg-red-400",
    tailwindBorder: "border-red-400",
    hoverBorder: "hover:border-red-400",
    hoverTextColor: "hover:text-red-400",
    tailwindTextColor: "text-red-400",
  },
  {
    name: "Produce",
    items: [
      "Egg White",
      "Espresso",
      "Heavy Cream",
      "Hot Coffee",
      "Lime Wedges",
      "Mint Leaves",
      "Olive Brine",
      "Sugar",
      "Sugar Cube",
    ],
    tailwindBG: "bg-emerald-800",
    tailwindBorder: "border-emerald-800",
    hoverBorder: "hover:border-emerald-800",
    hoverTextColor: "hover:text-emerald-800",
    tailwindTextColor: "text-emerald-800",
  },
  {
    name: "Miscellaneous",
    items: ["Red Wine"],
    tailwindBG: "bg-violet-900",
    tailwindBorder: "border-violet-900",
    hoverBorder: "hover:border-violet-900",
    hoverTextColor: "hover:text-violet-900",
    tailwindTextColor: "text-violet-900",
  },
];

export const allTags = [
  "Aperitif",
  "Bitter",
  "Bubbly",
  "Classic",
  "Citrusy",
  "Creamy",
  "Floral",
  "Fruity",
  "Hot",
  "Low ABV",
  "Modern Classic",
  "Personal Favorite",
  "Refreshing",
  "Rich",
  "Savory",
  "Simple",
  "Sour",
  "Spirit-Forward",
  "Sweet",
  "Tart",
  "Tiki",
];
